services:
  db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: pmrks
      POSTGRES_USER: pmrks
      POSTGRES_PASSWORD: pmrks
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.keystone/postgres:/var/lib/postgresql/data
