# fly.toml app configuration file generated for pmrks on 2023-12-18T14:22:01+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pmrks"
primary_region = "syd"
swap_size_mb = 1024

[build]
dockerfile = "Dockerfile.admin"

[build.args]
DB_PROVIDER = "postgresql"

[env]
KS_PORT = "3000"
NEXT_PUBLIC_GRAPHQL_PATH = "/api/graphql"
NEXT_PUBLIC_SERVER_URL = "https://pmrks.fly.dev"
STORE_IMAGE_BUCKET = "pmrks"
STORE_IMAGE_PREFIX = "images/"

# secrets
# DATABASE_URL = ""
# STORE_IMAGE_ACCESS_KEY_ID = ""
# STORE_IMAGE_SECRET_ACCESS_KEY = ""
# STORE_IMAGE_CUSTOM_URL = ""
# STORE_IMAGE_ENDPOINT = ""

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
