# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "zcm"
primary_region = "syd"
swap_size_mb = 256

[build]
dockerfile = "Dockerfile.admin"

[build.args]
DB_PROVIDER = "postgresql"

[env]
KS_PORT = "3000"

AWS_BUCKET = "zcm"

NEXT_PUBLIC_GRAPHQL_PATH = "/api/graphql"
NEXT_PUBLIC_SERVER_URL = "https://zcm.fly.dev"

# secrets

# DATABASE_URL = ""

# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
# AWS_CUSTOM_URL = ""
# AWS_ENDPOINT_URL = ""

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[deploy]
release_command = "npm run dbpush"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
